### ISSUE TITLE
400 Error HTTP method name strtolower!! Remove this!

### ISSUE THREAD

**Issue by xcartman** [basecrm/basecrm-php#35]
Method name must be in uppercase
https://github.com/basecrm/basecrm-php/blob/master/lib/HttpClient.php#L101

**Comment by AlCaughey** [comment]
Thanks.  Base has made some changes at their end and the problem seems to be fixed without the change you suggested.  

Regardless, if $method *must* be uppercase then rather that removing that line:
https://github.com/basecrm/basecrm-php/blob/master/lib/HttpClient.php#L101

It might be safer if the line is changed to:
```$method = strtoupper($method);
```

**Comment by efedasz** [comment]
Hi there.
We're sorry for the inconvenience. We've released a new version [v1.4.0](https://github.com/basecrm/basecrm-php/releases/tag/v1.4.0) with fixed HTTP method names.
We plan to upgrade our infrastructure, which can cause issues with older api-clients, so please upgrade your libraries.

Thank you!
